config/routes.rb
Rails.application.routes.draw do
  resources :people
  get 'people' => 'people#index'
  post 'people' => 'people#create'
  get 'people/index'

  get 'people/show'

  get 'people/new'

  get 'people/edit'

end

app/models/address.rb
class Address < ActiveRecord::Base
  validates_presence_of :city,:zip ,:street
  validates_numericality_of :zip

  validates_presence_of :state, :if => Proc.new { |addr| addr.country == "India"} # only validate if the country is India or proc returns true
  validates_length_of :state,:is=>2, :allow_blank => true

  belongs_to :person,:class_name => Person # always on the side where the foreign key is there

  before_save :default_county_if_blank
  
  private
  def default_county_if_blank
    if self.country.blank?
      self.country='India'
    end
  end
end

app/models/customer.rb
class Customer < Person
  has_many :orders,:dependent => :destroy do
    def most_recent
      order('created_at DESC').first
    end
  end

  #If you want to add conditions to your included models you’ll have to explicitly reference them. For example:

  # User.includes(:posts).where('posts.name = ?', 'example')
  #Doesn't JOIN the posts table, resulting in an error.

  #but this will work:
  # User.includes(:posts).where('posts.name = ?', 'example').references(:posts)
  #Query now knows the string references posts, so adds a JOIN

  scope :loyal_last_90_days,-> { includes(:orders).where('orders.created_at >= ?', 90.days.ago).references(:orders) }
  scope :min_2_items,->{ includes(:orders=>:order_items).where('order_items.id > 0').group('order_items.id,orders.id,people.id').having('COUNT(order_items.id) >= 2').references(:order_items)}

end

app/models/item.rb
class Item < ActiveRecord::Base

  validates_presence_of :name, :price

  has_many :order_items, :dependent => :destroy # if item gets deleted then its joined record also gets deleted

  scope :by_popularity,-> { includes(:order_items).group('items.id,order_items.id,order_items.item_id').order('COUNT(order_items.item_id) DESC').references(:order_items) }

end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :recipient,:sender,:subject
  belongs_to :sender,:class_name => Person
  belongs_to :recipient ,:class_name => Person
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :order_items, :dependent => :destroy
  has_many :items, :through => :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates_presence_of :first_name,:last_name  # should not be of zero length or nil
  has_many :addresses
  has_many :messages,:class_name => Message,:foreign_key => :recipient_id
  has_many :unread_messages,-> { where read_at: nil }, :class_name => Message , :foreign_key => :recipient_id
  accepts_nested_attributes_for :addresses  # works only when you have a association

  # benefits => are composable,  find_by_names_starting_with('text').count  will fire another SQl query for count
  #you can also do find_by_names_starting_with('text').addresses
  scope :find_by_names_starting_with, ->(term) {
    where("first_name LIKE :term OR last_name LIKE :term",:term=>term+"%").
    order('first_name ASC')
  }

  def full_name
    space=" "
    first_name<<space<<get_middle_name<<last_name
  end

  def add_address address
      self.addresses<<address
  end

  private

  def get_middle_name
    name=middle_name||""
    (name.blank?) ? name : (name<<" ")
  end

  #find records based on partial match on first or last name.
  #typing "Jon" -> Peter jones,Jona Smith

  # will return an array and    find_by_names_starting_with('text').count  will return size of array i.e does a ruby operation on it
  # def self.find_by_names_starting_with text
  #   Person.where("first_name LIKE :term OR last_name LIKE :term",:term=>text+"%").order('first_name ASC')
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people=Person.all
  end

  def show
  end

  def new
    @person=Person.new
    @person.addresses.build
  end

  def edit
  end

  # In order to build a deeply nested relationship like this, you will have to loop through your
  # "built" association , and invoke build again on its has_many association.
  def create
     @person=Person.new(person_params)
    (@person.save && (redirect_to people_path)) || (render 'new')
  end

  #to avoid ActiveModel::ForbiddenAttributesError error
  private
  def person_params
    params.require(:person).permit(:first_name, :last_name,addresses_attributes:[:city,:street,:zip,:state])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1>People#index</h1>
<h1>All People</h1>
<ul>
  <% @people.each do |p| %>
      <li>
        <%= link_to h(p.full_name), edit_person_path(p) %><br />
        <% addr = p.addresses.first %>
        <%if addr.present? %>
            <%=addr.street%>
            <%=addr.city%>
            <%=addr.state%>
            <%=addr.zip%>
        <%end%>
        <!--<%= h "#{addr.street}, #{addr.city}, #{addr.state}, #{addr.zip}" if addr.present? %>-->
      </li>
  <% end %>
</ul>
<%= link_to "New Person", new_person_path %>

app/views/people/new.html.erb
<h1>People#new</h1>

<!--When @person is new, uses people_path method to generate URL , PeopleController#create-->
<!--When @person exists already uses person_path method to generate URL, PeopleController#update-->

<%= form_for @person do |f| %>
    <p>
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </p>
    <p>
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </p>

    <%= f.fields_for :addresses do |addr| %>
        <div class="address">
          <p>
            <%= addr.label :street %><br />
            <%= addr.text_field :street %>
          </p>
          <p>
            <%= addr.label :city %><br />
            <%= addr.text_field :city %>
          </p>
          <p>
            <%= addr.label :state %><br />
            <%= addr.text_field :state %>
          </p>
          <p>
            <%= addr.label :zip %><br />
            <%= addr.text_field :zip %>
          </p>
        </div>
    <% end %>

    <p id="submit">
      <%= f.submit %>
    </p>

<% end  %>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>